import {buildMetadata} from "@/lib/metadata";
export const metadata=buildMetadata({"title":"Provisionii — People. Purpose. Possibility.","description":"Specialized recruiting and workforce solutions. Find your starting point with Provisionii.","path":"/"});
import { ArrowUpRight, ArrowRight } from '@/components/preview/Icons';
import Motion from '@/components/preview/Motion';
import Link from '@/components/static-link';
const audiences = [
 {id:'clients',number:'01',name:'For clients',title:'Build the team your work requires.',description:'Specialized professionals. A clearer workforce decision. The right starting point for the work ahead.',action:'Explore client solutions'},
 {id:'talent',number:'02',name:'For talent',title:'Make your next move meaningful.',description:'Bring your expertise, your ambitions, and your perspective to the conversation about what comes next.',action:'Explore the talent pathway'},
 {id:'partners',number:'03',name:'For partners',title:'Create opportunities together.',description:'Bring a client need, a contract placement, or specialist expertise. Explore the operating relationship that could make it possible.',action:'Explore partnerships'},
 {id:'suppliers',number:'04',name:'For suppliers',title:'Bring your strengths to the right relationship.',description:'Explore a potential supplier relationship built on defined capabilities, responsibilities, and engagement needs.',action:'Explore supplier relationships'},
];
export default function Home(){return <><section className="hero wrap"><div className="hero-overline"><div className="eyebrow"><span/> PROVISIONII WORKFORCE</div><span className="hero-aside">People at the center.</span></div><h1>The right people.<br/>For <span className="future">what comes next.</span></h1><div className="hero-bottom"><p>Provisionii connects organizations, professionals, and partners around the people that important work requires.</p><Link className="button" href="#pathways">Find your pathway <span><ArrowRight size={19}/></span></Link></div><div className="hero-footnote"><span>WORKFORCE, WITH PURPOSE.</span><Link href="#about">Meet Provisionii <span aria-hidden="true">↓</span></Link></div></section>
<section className="pathway-section" id="pathways"><div className="wrap"><div className="section-heading" data-reveal><div><p className="eyebrow">01 / YOUR CONNECTION</p><h2>Different paths.<br/>Shared possibility.</h2></div><p>Wherever you’re starting, <br/>there’s a place to begin.</p></div><div className="audience-grid">{audiences.map((a,i)=><Link className={'audience-card '+a.id} key={a.id} href={a.id === 'clients' ? '/find-talent' : a.id === 'talent' ? '/careers' : a.id === 'partners' ? '/contact?purpose=partnership' : '/contact?purpose=supplier'} data-reveal data-delay={i%2*65}><div className="card-top"><p className="card-label">{a.name}</p><span className="card-number">{a.number}</span></div><div className="card-body"><h3>{a.title}</h3><p className="card-description">{a.description}</p></div><div className="card-bottom"><span className="card-action">{a.action}</span><span className="card-arrow"><ArrowUpRight size={23}/></span></div></Link>)}</div></div></section>
<section className="about wrap" id="about"><div data-reveal><p className="eyebrow">02 / WHO WE ARE</p><h2>People at the center.<br/>Clarity at every step.</h2><div className="about-rule" aria-hidden="true"/></div><div className="about-copy" data-reveal><p className="lead">Important work deserves a thoughtful approach to people.</p><p>Provisionii is a workforce intelligence and operations company. We connect specialized professionals, organizations, and partners—and bring clarity to the relationships behind the work.</p><p>Some organizations need help finding the right people. Others bring known talent, a client opportunity, or an entire workforce program. We’re building the operating model that connects those starting points with intelligence and accountability.</p><Link className="text-link" href="/about">Get to know Provisionii <ArrowRight size={19}/></Link></div></section>
<section className="closing-shell"><div className="closing wrap" data-reveal><div className="closing-top"><span className="eyebrow">THE WORK AHEAD</span><span className="closing-mark" aria-hidden="true"/></div><h2>Great work begins<br/>with the right connection.</h2><div className="closing-bottom"><p>Let’s find your starting point.</p><Link className="button light" href="#pathways">Find yours <span><ArrowRight size={19}/></span></Link></div></div></section><Motion/></>}
